name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Now Global
      run: npm install -g vercel
    - name: Deploy to ZEIT Now
      run: |
        yarn install --frozen-lockfile
        yarn deploy
      env:
        CI: true
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} 
        BOT_TOKEN: ${{ secrets.BOT_KEY }}
        WEB_DOMAIN: ${{ secrets.WEB_DOMAIN }}
